
on:
  pull_request:
    types: [ synchronize, opened ]
    branches:
        - master
        - 'v[0-9]+.*' # release branch
        - ci-test # testing branch for github action
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: ./scripts/format-all.sh
      - name: ci
        run: ./scripts/travis.sh
